# Generated by Django 5.2.8 on 2025-12-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceipal_Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=512)),
                ('refresh_token', models.CharField(max_length=512)),
                ('access_token_issued_at', models.DateTimeField(auto_now_add=True)),
                ('access_token_updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token_issued_at', models.DateTimeField(auto_now_add=True)),
                ('refresh_token_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
