# Generated by Django 5.2 on 2025-05-01 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCoordinator',
            fields=[
                ('account_coordinator_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_coordinator', models.CharField(max_length=100, verbose_name='Account Coordinator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('account_head_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Account Coordinator',
                'verbose_name_plural': 'Account Coordinators',
            },
        ),
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('account_head_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_head', models.CharField(max_length=100, verbose_name='Account Head')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('account_head_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Account Head',
                'verbose_name_plural': 'Account Heads',
            },
        ),
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('account_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_manager', models.CharField(max_length=100, verbose_name='Account Manager')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('account_manager_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Account Manager',
                'verbose_name_plural': 'Account Managers',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=100, verbose_name='Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HiringManager',
            fields=[
                ('hiring_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('hiring_manager', models.CharField(max_length=100, verbose_name='Hiring Manager')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('hiring_manager_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Hiring Manager',
                'verbose_name_plural': 'Hiring Managers',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_date', models.DateField(verbose_name='Holiday Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('job_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_status', models.CharField(max_length=100, verbose_name='Job Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('recruiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruiter_name', models.CharField(max_length=100, verbose_name='Recruiter Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('recruiter_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Role_Type',
            fields=[
                ('role_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=100, verbose_name='Role Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screening_Status',
            fields=[
                ('screening_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('screening_status', models.CharField(max_length=100, verbose_name='Screening Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sourcer',
            fields=[
                ('sourcer_id', models.AutoField(primary_key=True, serialize=False)),
                ('sourcer_name', models.CharField(max_length=100, verbose_name='Sourcer Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('sourcer_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Tech_Screener',
            fields=[
                ('tech_screener_id', models.AutoField(primary_key=True, serialize=False)),
                ('tech_screener_name', models.CharField(max_length=100, verbose_name='Tech Screener Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('tech_screener_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('account_status', models.BooleanField(default=True, verbose_name='Active')),
                ('account_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.accountcoordinator', verbose_name='Account Coordinator')),
                ('account_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.accounthead', verbose_name='Account Head')),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.accountmanager', verbose_name='Account Manager')),
            ],
        ),
        migrations.CreateModel(
            name='EndClient',
            fields=[
                ('end_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_client_name', models.CharField(max_length=100, verbose_name='End Client Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('end_client_status', models.BooleanField(default=True, verbose_name='Active')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.account', verbose_name='Account Name')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('client_status', models.BooleanField(default=True, verbose_name='Active')),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.endclient', verbose_name='End Client Name')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_code', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=200)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.account')),
                ('accountManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.accountmanager')),
                ('assigned_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_recruiter', to='ta_team.recruiter')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.client', verbose_name='Client Name')),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.endclient')),
                ('filled_by_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_recruiter', to='ta_team.recruiter')),
                ('hiringManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.hiringmanager')),
                ('job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.jobstatus')),
                ('filled_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.source')),
                ('assigned_sourcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sourcer', to='ta_team.sourcer')),
                ('filled_by_sourcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_sourcer', to='ta_team.sourcer')),
            ],
        ),
    ]
