# Generated by Django 5.2 on 2025-05-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account Name', 'verbose_name_plural': 'Account Names'},
        ),
        migrations.AlterField(
            model_name='requirements',
            name='filled_by_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filled_recruiter', to='ta_team.recruiter'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='filled_by_sourcer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filled_sourcer', to='ta_team.sourcer'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='filled_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ta_team.source'),
        ),
    ]
