# Generated by Django 5.2 on 2025-04-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='createAccount',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
                ('account_coordinator', models.CharField(max_length=100)),
                ('account_manager', models.CharField(max_length=100)),
                ('account_head', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('account_status', models.CharField(default='Active', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='createUser',
        ),
    ]
