# Generated by Django 5.2 on 2025-04-21 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0002_createaccount_delete_createuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
                ('account_coordinator', models.CharField(max_length=100)),
                ('account_head', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('account_status', models.CharField(default='Active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('account_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_manager', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='createAccount',
        ),
        migrations.AddField(
            model_name='account',
            name='account_manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.accountmanager'),
        ),
    ]
