# Generated by Django 5.2 on 2025-05-21 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0002_alter_account_options_requirements_role_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_date', models.DateField()),
                ('candidate_name', models.CharField(max_length=100)),
                ('payrate', models.IntegerField(blank=True, null=True)),
                ('w2_C2C', models.CharField(blank=True, null=True)),
                ('am_sub_date', models.DateField()),
                ('am_screen_date', models.DateField(blank=True, null=True)),
                ('tech_screen_date', models.DateField(blank=True, null=True)),
                ('client_sub_date', models.DateField(blank=True, null=True)),
                ('client_interview_date', models.DateField(blank=True, null=True)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.requirements')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.recruiter')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.source')),
                ('sourcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.sourcer')),
            ],
        ),
    ]
