# Generated by Django 5.2 on 2025-04-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0003_account_accountmanager_delete_createaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_manager_id',
            new_name='account_manager',
        ),
    ]
