# Generated by Django 5.2 on 2025-05-22 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0003_submissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_code', models.CharField(max_length=10, unique=True)),
                ('emp_fName', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_lName', models.CharField(blank=True, max_length=50, null=True)),
                ('can_recruit', models.BooleanField(default=True)),
                ('can_source', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.designation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
