# Generated by Django 5.2 on 2025-04-21 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0004_rename_account_manager_id_account_account_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('account_head_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_head', models.CharField(max_length=100, verbose_name='Account Head')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('account_head_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.AddField(
            model_name='accountmanager',
            name='account_manager_status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.accountmanager', verbose_name='Account Manager'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(max_length=100, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='account_manager',
            field=models.CharField(max_length=100, verbose_name='Account Manager'),
        ),
        migrations.AlterField(
            model_name='accountmanager',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.accounthead', verbose_name='Account Head'),
        ),
    ]
