# Generated by Django 5.2 on 2025-05-26 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0004_department_designation_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='assigned_recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_recruiter', to='ta_team.employee'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='assigned_sourcer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sourcer', to='ta_team.employee'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='filled_by_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filled_recruiter', to='ta_team.employee'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='filled_by_sourcer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filled_sourcer', to='ta_team.employee'),
        ),
    ]
