# Generated by Django 5.2 on 2025-04-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0005_accounthead_accountmanager_account_manager_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=100, verbose_name='Feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_date', models.DateField(verbose_name='Holiday Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('job_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_status', models.CharField(max_length=100, verbose_name='Job Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('recruiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('recruiter_name', models.CharField(max_length=100, verbose_name='Recruiter Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('recruiter_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Role_Type',
            fields=[
                ('role_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=100, verbose_name='Role Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screening_Status',
            fields=[
                ('screening_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('screening_status', models.CharField(max_length=100, verbose_name='Screening Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sourcer',
            fields=[
                ('sourcer_id', models.AutoField(primary_key=True, serialize=False)),
                ('sourcer_name', models.CharField(max_length=100, verbose_name='Sourcer Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('sourcer_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Tech_Screener',
            fields=[
                ('tech_screener_id', models.AutoField(primary_key=True, serialize=False)),
                ('tech_screener_name', models.CharField(max_length=100, verbose_name='Tech Screener Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('tech_screener_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.AlterModelOptions(
            name='accounthead',
            options={'verbose_name': 'Account Head', 'verbose_name_plural': 'Account Heads'},
        ),
        migrations.AlterModelOptions(
            name='accountmanager',
            options={'verbose_name': 'Account Manager', 'verbose_name_plural': 'Account Managers'},
        ),
        migrations.CreateModel(
            name='EndClient',
            fields=[
                ('end_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_client_name', models.CharField(max_length=100, verbose_name='End Client Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('end_client_status', models.BooleanField(default=True, verbose_name='Active')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.account', verbose_name='Account Name')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('client_status', models.BooleanField(default=True, verbose_name='Active')),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.endclient', verbose_name='End Client Name')),
            ],
        ),
    ]
