# Generated by Django 5.2 on 2025-05-26 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0005_alter_requirements_assigned_recruiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_recruiter', to='ta_team.employee'),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='sourcer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_sourcer', to='ta_team.employee'),
        ),
    ]
