# Generated by Django 5.2 on 2025-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0006_feedback_holiday_jobstatus_recruiter_role_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCoordinator',
            fields=[
                ('account_coordinator_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_coordinator', models.CharField(max_length=100, verbose_name='Account Coordinator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('account_head_status', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Account Coordinator',
                'verbose_name_plural': 'Account Coordinators',
            },
        ),
    ]
