# Generated by Django 5.2 on 2025-05-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0006_alter_submissions_recruiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='req_opened_date',
            field=models.DateField(default='2025-05-30'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requirements',
            name='job_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
