# Generated by Django 5.2 on 2025-06-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0007_requirements_req_opened_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='no_of_positions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requirements',
            name='no_of_positions_filled',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
