# Generated by Django 5.2 on 2025-04-21 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0007_accountcoordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.accountcoordinator', verbose_name='Account Coordinator'),
        ),
    ]
