# Generated by Django 5.2 on 2025-04-27 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0008_alter_account_account_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_code', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=200)),
                ('offer_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.account')),
                ('assigned_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_recruiter', to='ta_team.recruiter')),
                ('assigned_sourcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sourcer', to='ta_team.sourcer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.client', verbose_name='Client Name')),
                ('end_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.endclient')),
                ('filled_by_recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_recruiter', to='ta_team.recruiter')),
                ('filled_by_sourcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_sourcer', to='ta_team.sourcer')),
                ('filled_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.source')),
                ('job_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.jobstatus')),
            ],
        ),
    ]
