# Generated by Django 5.2 on 2025-06-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0008_requirements_no_of_positions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirements',
            old_name='offer_date',
            new_name='filled_date',
        ),
    ]
