# Generated by Django 5.2 on 2025-06-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0009_rename_offer_date_requirements_filled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonForLeaving',
            fields=[
                ('reason_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('placment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.requirements')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.submissions')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ta_team.reasonforleaving')),
            ],
        ),
    ]
