# Generated by Django 5.2 on 2025-06-18 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0010_reasonforleaving_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('role_permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('Permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.designation')),
            ],
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
        migrations.DeleteModel(
            name='Sourcer',
        ),
    ]
