# Generated by Django 5.2 on 2025-06-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0011_permission_rolepermission_delete_recruiter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_created_by', to='ta_team.employee'),
        ),
        migrations.AddField(
            model_name='submissions',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions_created_by', to='ta_team.employee'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='permission',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
