# Generated by Django 5.2 on 2025-06-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0012_requirements_created_by_submissions_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepermission',
            name='Permission',
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='role',
        ),
        migrations.AddField(
            model_name='designation',
            name='access_Analytics',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='complete_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='delete_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='delete_own_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='edit_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='edit_own_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='only_Recruiter_Analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='only_client_Analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='only_sourcer_Analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='designation',
            name='only_submission_Analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='RolePermission',
        ),
    ]
