# Generated by Django 5.2 on 2025-06-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0013_remove_rolepermission_permission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placement',
            old_name='reason',
            new_name='reason_for_leaving',
        ),
        migrations.AddField(
            model_name='placement',
            name='Contract_end_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
