# Generated by Django 5.2 on 2025-06-29 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0014_rename_reason_placement_reason_for_leaving_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirements',
            name='filled_by_recruiter',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='filled_by_sourcer',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='filled_source',
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
