# Generated by Django 5.2 on 2025-06-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0015_remove_requirements_filled_by_recruiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='assigned_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_recruiter', to='ta_team.employee'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='assigned_sourcer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_sourcer', to='ta_team.employee'),
        ),
    ]
