# Generated by Django 5.2 on 2025-06-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0016_alter_requirements_assigned_recruiter_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='requirements',
            index=models.Index(fields=['req_opened_date'], name='ta_team_req_req_ope_2f9674_idx'),
        ),
        migrations.AddIndex(
            model_name='requirements',
            index=models.Index(fields=['client'], name='ta_team_req_client__3ad196_idx'),
        ),
        migrations.AddIndex(
            model_name='requirements',
            index=models.Index(fields=['end_client'], name='ta_team_req_end_cli_a154ef_idx'),
        ),
        migrations.AddIndex(
            model_name='requirements',
            index=models.Index(fields=['job_status'], name='ta_team_req_job_sta_e19892_idx'),
        ),
        migrations.AddIndex(
            model_name='requirements',
            index=models.Index(fields=['assigned_recruiter'], name='ta_team_req_assigne_c3c8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='requirements',
            index=models.Index(fields=['assigned_sourcer'], name='ta_team_req_assigne_da24b7_idx'),
        ),
        migrations.AddIndex(
            model_name='requirements',
            index=models.Index(fields=['role_type'], name='ta_team_req_role_ty_9c898b_idx'),
        ),
    ]
