# Generated by Django 5.2 on 2025-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0017_requirements_ta_team_req_req_ope_2f9674_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['Job'], name='ta_team_sub_Job_id_1b71f1_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['recruiter'], name='ta_team_sub_recruit_07eb67_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['sourcer'], name='ta_team_sub_sourcer_0d91a3_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['submission_date'], name='ta_team_sub_submiss_ff870c_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['client_sub_date'], name='ta_team_sub_client__a04be8_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['start_date'], name='ta_team_sub_start_d_5a3d17_idx'),
        ),
    ]
