# Generated by Django 5.2 on 2025-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0018_submissions_ta_team_sub_job_id_1b71f1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submissions',
            name='ta_team_sub_start_d_5a3d17_idx',
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['current_status'], name='ta_team_sub_current_9fd6a3_idx'),
        ),
    ]
