# Generated by Django 5.2 on 2025-06-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0019_remove_submissions_ta_team_sub_start_d_5a3d17_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['Job'], name='ta_team_pla_Job_id_08e1a2_idx'),
        ),
    ]
