# Generated by Django 5.2 on 2025-07-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0020_placement_ta_team_pla_job_id_08e1a2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardJobData',
            fields=[
                ('req_opened_date', models.DateField(primary_key=True, serialize=False)),
                ('job_code', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('filled_date', models.DateField(null=True)),
                ('client_id', models.IntegerField(null=True)),
                ('end_client_id', models.IntegerField(null=True)),
                ('account_id', models.IntegerField(null=True)),
                ('job_status_id', models.IntegerField(null=True)),
                ('role_type_id', models.IntegerField(null=True)),
                ('end_client_name', models.CharField(max_length=255, null=True)),
                ('account_name', models.CharField(max_length=255, null=True)),
                ('job_status', models.CharField(max_length=100, null=True)),
                ('role_type', models.CharField(max_length=100, null=True)),
                ('amsubs', models.IntegerField(null=True)),
                ('csubs', models.IntegerField(null=True)),
                ('interviews', models.IntegerField(null=True)),
                ('offers', models.IntegerField(null=True)),
                ('starts', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'req_submissions',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='requirements',
            name='notes',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
