# Generated by Django 5.2 on 2025-07-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0021_dashboardjobdata_alter_requirements_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='payrate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
