# Generated by Django 5.2 on 2025-07-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0022_alter_submissions_payrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='turn_around_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
