# Generated by Django 5.2.8 on 2026-01-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0023_submissions_turn_around_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100, verbose_name='Module Name')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionType',
            fields=[
                ('permission_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_type_name', models.CharField(max_length=100, verbose_name='Permission Type Name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobstatus',
            options={'verbose_name': 'Job Status', 'verbose_name_plural': 'Job Statuses'},
        ),
        migrations.AlterModelOptions(
            name='reasonforleaving',
            options={'verbose_name': 'Reason For Leaving', 'verbose_name_plural': 'Reasons For Leaving'},
        ),
        migrations.AlterModelOptions(
            name='role_type',
            options={'verbose_name': 'Role Type', 'verbose_name_plural': 'Role Types'},
        ),
        migrations.AlterModelOptions(
            name='screening_status',
            options={'verbose_name': 'Screening Status', 'verbose_name_plural': 'Screening Statuses'},
        ),
        migrations.AlterModelOptions(
            name='tech_screener',
            options={'verbose_name': 'Technical Screener', 'verbose_name_plural': 'Technical Screeners'},
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('role_permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.designation', verbose_name='Designation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.module', verbose_name='Module')),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.permissiontype', verbose_name='Permission Type')),
            ],
            options={
                'unique_together': {('designation', 'module', 'permission_type')},
            },
        ),
    ]
