# Generated by Django 5.2.8 on 2026-02-22 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0024_module_permissiontype_alter_jobstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetforTeam',
            fields=[
                ('target_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Year')),
                ('target_am_submissions', models.IntegerField(verbose_name='Target Submissions')),
                ('target_c_submissions', models.IntegerField(verbose_name='Target C Submissions')),
                ('target_offers', models.IntegerField(verbose_name='Target Offers')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.employee', verbose_name='Employee')),
            ],
            options={
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
