# Generated by Django 5.2.8 on 2026-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0025_targetforteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='loop_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissions',
            name='loop_closed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='loop_closed_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
