# Generated by Django 5.2.8 on 2026-03-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0026_submissions_loop_closed_submissions_loop_closed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Module Code'),
        ),
    ]
