# Generated by Django 5.2.8 on 2026-04-08 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0027_module_module_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100, verbose_name='Status Name')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('main_table_field', models.CharField(blank=True, max_length=50, null=True, verbose_name='Main Table Field')),
            ],
            options={
                'verbose_name': 'Submission Status',
                'verbose_name_plural': 'Submission Statuses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionStatusLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.submissionstatus')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='ta_team.submissions')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ta_team.employee')),
            ],
            options={
                'verbose_name': 'Submission Status Log',
                'verbose_name_plural': 'Submission Status Logs',
                'indexes': [models.Index(fields=['submission'], name='ta_team_sub_submiss_5cd22d_idx'), models.Index(fields=['status'], name='ta_team_sub_status__333938_idx')],
                'unique_together': {('submission', 'status')},
            },
        ),
    ]
