# Generated by Django 5.2.8 on 2026-04-08 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0028_5_seed_submissionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='current_new_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ta_team.submissionstatus'),
        ),
    ]
