# Generated by Django 5.2.8 on 2026-04-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0029_submissions_current_new_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='requirements',
            index=models.Index(fields=['account'], name='ta_team_req_account_4d888d_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['source'], name='ta_team_sub_source__bd1b40_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['current_new_status'], name='ta_team_sub_current_21b935_idx'),
        ),
    ]
