# Generated by Django 5.2.8 on 2026-05-03 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0032_requirements_job_search_trgm_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_Screen',
            fields=[
                ('tech_screen_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Feedback')),
                ('screening_date', models.DateField(verbose_name='Screening Date')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.requirements', verbose_name='Job Code')),
                ('screening_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.screening_status', verbose_name='Screening Status')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.submissions', verbose_name='Submission')),
                ('tech_screener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_team.tech_screener', verbose_name='Tech Screener')),
            ],
        ),
    ]
