# Generated by Django 5.2.8 on 2026-05-04 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0033_tech_screen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_screen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='tech_screen',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ta_team.employee', verbose_name='Updated By'),
        ),
        migrations.AlterUniqueTogether(
            name='tech_screen',
            unique_together={('job', 'submission', 'tech_screen_id')},
        ),
    ]
