# Generated by Django 5.2.8 on 2026-06-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_team', '0034_tech_screen_updated_at_tech_screen_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tech_screen',
            name='feedback',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Feedback'),
        ),
    ]
